# -*- coding: utf-8 -*-
"""SuperStore Sales Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ICrEwDWJ7HnB9_reU3GSaDftF41pErjn

📊 Superstore Sales Data Analysis Project  
### Business Intelligence & Exploratory Data Analysis using Python  

---

## 🎯 Project Objective  

This project analyzes 3 years of retail sales data to answer key business questions:

1. What is the overall sales trend?
2. Which are the Top 10 products by sales?
3. Which are the Most Selling Products (by quantity)?
4. Which is the most preferred Ship Mode?
5. Which are the Most Profitable Category and Sub-Category?

---

## 🛠 Tools & Libraries Used  

- Python  
- Pandas  
- Matplotlib  
- Seaborn  
- Google Colab  

---

#  STEP 1: Import Required Libraries


import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

## 📂 STEP 2: Upload & Load Dataset
"""

from google.colab import files
uploaded = files.upload()

df = pd.read_excel(list(uploaded.keys())[0])

df.head()

"""## 🧹 STEP 3: Data Cleaning & Standardization  

To avoid column name errors, we standardize all column names.

"""

# Standardizing column names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print(df.columns)

"""## 🔍 STEP 4: Data Audit  

Understanding the dataset structure before analysis.

"""

df.shape
df.info()
df.describe()
df.isnull().sum()

"""## 🗓 STEP 5: Date Conversion & Feature Engineering  

We extract year and month to analyze trends over time.

"""

df["order_date"] = pd.to_datetime(df["order_date"])

df["year"] = df["order_date"].dt.year
df["month"] = df["order_date"].dt.month
df["month_name"] = df["order_date"].dt.month_name()

df.head()

"""# 📈 Business Question 1  
## What is the Overall Sales Trend?

"""

monthly_sales = (
    df.groupby(df["order_date"].dt.to_period("M"))["sales"]
    .sum()
)

monthly_sales.plot(figsize=(12,5))
plt.title("Overall Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.show()

"""### 🔎 Insight:
Sales show a growing trend over the years, indicating business expansion and seasonal patterns.

# 📊 Business Question 2  
## Top 10 Products by Sales
"""

top_products = (
    df.groupby("product_name")["sales"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_products.plot(kind="bar", figsize=(12,5))
plt.title("Top 10 Products by Sales")
plt.ylabel("Sales")
plt.show()

"""### 🔎 Insight:
These products generate the highest revenue and are key drivers of overall sales performance.

"""

most_selling = (
    df.groupby("product_name")["quantity"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

most_selling.plot(kind="bar", figsize=(12,5))
plt.title("Most Selling Products by Quantity")
plt.ylabel("Quantity Sold")
plt.show()

"""### 🔎 Insight:
High quantity products are not always the highest revenue products, indicating pricing differences.

# 🚚 Business Question 4  
## Most Preferred Ship Mode
"""

ship_mode_counts = df["ship_mode"].value_counts()

ship_mode_counts.plot(kind="bar")
plt.title("Most Preferred Ship Mode")
plt.ylabel("Number of Orders")
plt.show()

"""### 🔎 Insight:
Understanding shipping preference helps optimize logistics strategy and cost management.

# 💰 Business Question 5  
## Most Profitable Category & Sub-Category
"""

category_profit = df.groupby("category")["profit"].sum()

category_profit.plot(kind="bar")
plt.title("Profit by Category")
plt.ylabel("Profit")
plt.show()

sub_category_profit = (
    df.groupby("sub_category")["profit"]
    .sum()
    .sort_values(ascending=False)
)

sub_category_profit.plot(kind="bar", figsize=(14,5))
plt.title("Profit by Sub-Category")
plt.ylabel("Profit")
plt.show()

"""### 🔎 Insight:
Some sub-categories generate high revenue but low profit, indicating potential discount or cost issues.

# 📉 Advanced Analysis  
## Sales vs Profit Relationship
"""

sns.scatterplot(data=df, x="sales", y="profit")
plt.title("Sales vs Profit Relationship")
plt.show()

"""## 🏁 Final Conclusion  

- Sales show steady growth over time.
- A small group of products drives majority revenue.
- High sales does not always mean high profit.
- Shipping preferences affect operational strategy.
- Profit optimization requires category-level strategy.

---

## 📌 Key Takeaways  

This project demonstrates:
- Data Cleaning
- Feature Engineering
- GroupBy Aggregation
- Data Visualization
- Business Insight Extraction

---

### 🔗 Built using Python | Pandas | Matplotlib | Seaborn | Google Colab

"""